service: repox-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
